### ISSUE TITLE
Stream.from*Instream does not close the input stream when finished

### ISSUE THREAD

**Issue by finrod** [standardml/cmlib#5]
It is unclear to me whether `Stream.fromTextInstream` (and the Bin variant) should close the stream when the end is reached. In the current implementation it doesn't, which is slightly troublesome when the function is used to read files: one has to keep the stream around and manually close it when the file ends; this is quite cumbersome since the stream is lazy and it's nontrivial to determine the point at which the stream should be closed. Is this done on purpose (and if so, what is the use-case the authors have in mind), or is this an oversight?

**Comment by kcrary** [comment]
It's now implemented in 9a50f22.
